name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions: write-all

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Bundle JSON Schemas
        run: |
          pnpm install
          pnpm run release

      - name: Upload Schemas
        uses: actions/upload-artifact@v4
        with:
          name: schemas
          path: schemas/*
          overwrite: true
          if-no-files-found: error

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "ci: release ${{ github.ref_name }}"
          push: origin HEAD:main

  github-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Schemas
        uses: actions/download-artifact@v4

      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          make_latest: true
          files: schemas/*

  npm-publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Download Schemas
        uses: actions/download-artifact@v4

      - name: NPM Publish
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
